### ISSUE TITLE
Weekly reports aren't being sent

### ISSUE THREAD

**Issue by seanjhardy** [Project-Skill-Tree/Skill-Tree-Discord-Bot#82]
**Describe the bug**
Weekly reports are supposed to send at 6PM every Sunday, localised to every user's timezone. The weekly report does not actually send at this time and there is no error.

**To Reproduce**
N/A

**Expected behavior**
A weekly report sent to the assigned botChannel in the user's base at 6PM on Sunday

**Comment by iJynx** [comment]
I'm not completely sure about htis one since I have 0 experience with Cron but could it be that the Cron config is incorrect. According to [this cron calculator](https://crontab.guru/#0_0-24/30_*_*_6,0,1) your cron config is set to run at `“At minute 0 past every 30th hour from 0 through 24 on Saturday, Sunday, and Monday.”`
